# Generated by Django 5.2.1 on 2025-05-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_remove_letting_address_alter_profile_id_and_more'),
    ]

    operations = [
    ]
